# Generated by Django 6.0 on 2025-12-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userlike",
            name="ip_address",
            field=models.GenericIPAddressField(),
        ),
    ]
