# Generated by Django 6.0 on 2025-12-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userlike_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='is_profane',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='word',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='word',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
