# Generated by Django 6.0 on 2025-12-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_word_is_profane_alter_word_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='word',
            name='author',
            field=models.CharField(default='Anonim', max_length=50),
        ),
    ]
