# Generated by Django 6.0 on 2025-12-20 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20251221_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='likes_count',
        ),
        migrations.DeleteModel(
            name='UserLike',
        ),
    ]
