# Generated by Django 6.0 on 2025-12-22 13:22

from django.db import migrations, models
from django.db.models import F

def copy_ip_to_session(apps, schema_editor):
    """
    Copies the existing IP address into the new session_id field
    to ensure every vote has a unique session_id before we add constraints.
    """
    WordVote = apps.get_model('core', 'WordVote')
    CommentVote = apps.get_model('core', 'CommentVote')
    
    # Copy ip_address to session_id for all existing rows
    WordVote.objects.update(session_id=F('ip_address'))
    CommentVote.objects.update(session_id=F('ip_address'))

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_word_likes_count_delete_userlike'),
    ]

    operations = [
        # 1. Remove old constraints first
        migrations.AlterUniqueTogether(
            name='commentvote',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='wordvote',
            unique_together=set(),
        ),

        # 2. Add session_id as NULLABLE first (so we can fill it)
        migrations.AddField(
            model_name='commentvote',
            name='session_id',
            field=models.CharField(db_index=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='wordvote',
            name='session_id',
            field=models.CharField(db_index=True, max_length=40, null=True),
        ),

        # 3. Run Python script to fill session_id with old IP addresses
        migrations.RunPython(copy_ip_to_session),

        # 4. Now that data is filled, make session_id NOT NULL
        migrations.AlterField(
            model_name='commentvote',
            name='session_id',
            field=models.CharField(db_index=True, max_length=40, default='legacy'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wordvote',
            name='session_id',
            field=models.CharField(db_index=True, max_length=40, default='legacy'),
            preserve_default=False,
        ),

        # 5. Make IP Address Nullable (as you requested)
        migrations.AlterField(
            model_name='commentvote',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wordvote',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),

        # 6. Finally, apply the new Unique Constraints
        migrations.AlterUniqueTogether(
            name='commentvote',
            unique_together={('session_id', 'comment')},
        ),
        migrations.AlterUniqueTogether(
            name='wordvote',
            unique_together={('session_id', 'word')},
        ),
    ]