# Generated by Django 6.0 on 2025-12-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_word_likes_count_delete_userlike'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentvote',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='wordvote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='commentvote',
            name='session_id',
            field=models.CharField(db_index=True, default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wordvote',
            name='session_id',
            field=models.CharField(db_index=True, default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commentvote',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wordvote',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='commentvote',
            unique_together={('session_id', 'comment')},
        ),
        migrations.AlterUniqueTogether(
            name='wordvote',
            unique_together={('session_id', 'word')},
        ),
    ]
