# Generated by Django 6.0 on 2026-01-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_comment_user_commentvote_user_word_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
