# Generated by Django 6.0 on 2026-01-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_word_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='example',
            field=models.CharField(default='', max_length=200),
        ),
    ]
