# Generated by Django 6.0 on 2026-03-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_category_word_example_word_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='etymology',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
