# Generated by Django 6.0 on 2026-03-22 11:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_word_etymology'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentvote',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='wordvote',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='commentvote',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='etymology',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='wordvote',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
        migrations.AddConstraint(
            model_name='commentvote',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'comment'), name='unique_user_comment_vote'),
        ),
        migrations.AddConstraint(
            model_name='commentvote',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('session_id', 'comment'), name='unique_session_comment_vote'),
        ),
        migrations.AddConstraint(
            model_name='wordvote',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'word'), name='unique_user_word_vote'),
        ),
        migrations.AddConstraint(
            model_name='wordvote',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('session_id', 'word'), name='unique_session_word_vote'),
        ),
    ]
