# Generated by Django 6.0 on 2026-03-22 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_commentvote_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='commentvote',
            name='unique_user_comment_vote',
        ),
        migrations.RemoveConstraint(
            model_name='commentvote',
            name='unique_session_comment_vote',
        ),
        migrations.RemoveConstraint(
            model_name='wordvote',
            name='unique_user_word_vote',
        ),
        migrations.RemoveConstraint(
            model_name='wordvote',
            name='unique_session_word_vote',
        ),
        migrations.AlterUniqueTogether(
            name='commentvote',
            unique_together={('user', 'comment')},
        ),
        migrations.AlterUniqueTogether(
            name='wordvote',
            unique_together={('user', 'word')},
        ),
        migrations.AlterField(
            model_name='commentvote',
            name='user',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, related_name='comment_votes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wordvote',
            name='user',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, related_name='word_votes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='commentvote',
            name='session_id',
        ),
        migrations.RemoveField(
            model_name='wordvote',
            name='session_id',
        ),
    ]
