# Generated by Django 6.0 on 2026-03-26 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_commentvote_unique_user_comment_vote_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='is_profane',
        ),
    ]
