# Generated by Django 6.0 on 2026-04-02 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_translationchallenge_challengecomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengecomment',
            name='explanation',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='challengecomment',
            name='suggested_word',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='challengecomment',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
