# Generated by Django 6.0 on 2026-04-02 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_challengecomment_explanation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengecomment',
            name='comment',
        ),
        migrations.AlterField(
            model_name='challengecomment',
            name='suggested_word',
            field=models.CharField(max_length=30),
        ),
    ]
