# Generated by Django 6.0 on 2026-04-09 11:24

import re
from django.db import migrations, models


TURKISH_CHAR_MAP = {
    'ç': 'c', 'ğ': 'g', 'ı': 'i', 'ö': 'o', 'ş': 's', 'ü': 'u',
    'â': 'a', 'î': 'i', 'û': 'u',
}


def turkish_to_ascii(text):
    text = text.lower()
    for tr, en in TURKISH_CHAR_MAP.items():
        text = text.replace(tr, en)
    text = re.sub(r'[^a-z0-9]+', '-', text)
    return text.strip('-')


def populate_slugs(apps, schema_editor):
    Word = apps.get_model('core', 'Word')
    seen = {}
    for word in Word.objects.order_by('id'):
        base = turkish_to_ascii(word.word)
        count = seen.get(base, 0) + 1
        seen[base] = count
        word.slug = base if count == 1 else f'{base}{count}'
        word.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_word_rejection_reason_alter_word_status_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='slug',
            field=models.SlugField(max_length=80, null=True, unique=True),
        ),
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
    ]
