# core/migrations/0023_alter_notification_notification_type.py
# Generated by Django 6.0 on 2026-04-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_comment_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(
                choices=[
                    ('word_like', 'Word Like'), 
                    ('word_dislike', 'Word Dislike'), 
                    ('comment_like', 'Comment Like'), 
                    ('comment_dislike', 'Comment Dislike'), 
                    ('challenge_like', 'Challenge Like'), 
                    ('challenge_dislike', 'Challenge Dislike'), 
                    ('new_comment', 'New Comment'), 
                    ('challenge_win', 'Challenge Win'), 
                    ('word_rejected', 'Word Rejected'), 
                    ('challenge_rejected', 'Challenge Rejected')
                ], 
                max_length=20
            ),
        ),
    ]