# Generated by Django 6.0 on 2026-04-11 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0008_rename_challenge_cc_challenge_score_idx_core_challe_challen_ff213f_idx'),
        ('core', '0023_alter_notification_notification_type'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='comment',
            new_name='core_commen_word_id_1d0a38_idx',
            old_name='core_commen_word_id_timestamp_idx',
        ),
        migrations.AddField(
            model_name='notification',
            name='challenge_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='challenge.challengecomment'),
        ),
    ]
