# Generated by Django 6.0 on 2026-04-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_notification_notification_type'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='comment',
            new_name='core_commen_word_id_1d0a38_idx',
            old_name='core_commen_word_id_timestamp_idx',
        ),
    ]
