# Generated by Django 6.0 on 2026-04-11 19:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_rename_core_commen_word_id_timestamp_idx_core_commen_word_id_1d0a38_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='core_notifi_recipie_b4f908_idx',
        ),
        migrations.AddField(
            model_name='notification',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_active', 'is_read', '-timestamp'], name='core_notifi_recipie_b7a566_idx'),
        ),
    ]
