# Generated by Django 6.0.5 on 2026-07-21 09:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_notification_core_notifi_recipie_b4f908_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('username_snapshot', models.CharField(blank=True, default='', max_length=150)),
                ('is_authenticated', models.BooleanField(db_index=True, default=False)),
                ('session_key', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('method', models.CharField(db_index=True, max_length=12)),
                ('path', models.CharField(max_length=2048)),
                ('route_name', models.CharField(blank=True, db_index=True, default='', max_length=150)),
                ('view_name', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('query_params', models.JSONField(blank=True, default=dict)),
                ('request_data', models.JSONField(blank=True, default=dict)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('referer', models.TextField(blank=True, default='')),
                ('status_code', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('response_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('error_type', models.CharField(blank=True, default='', max_length=255)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='FunctionCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('username_snapshot', models.CharField(blank=True, default='', max_length=150)),
                ('is_authenticated', models.BooleanField(db_index=True, default=False)),
                ('session_key', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('module', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('function_name', models.CharField(db_index=True, max_length=255)),
                ('label', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('arguments', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], db_index=True, default='success', max_length=16)),
                ('duration_ms', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('error_type', models.CharField(blank=True, default='', max_length=255)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='function_call_logs', to=settings.AUTH_USER_MODEL)),
                ('request_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='function_calls', to='core.requestlog')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['user', '-started_at'], name='core_reques_user_id_b3e1ff_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['ip_address', '-started_at'], name='core_reques_ip_addr_445827_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['route_name', '-started_at'], name='core_reques_route_n_4b648d_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['status_code', '-started_at'], name='core_reques_status__ea87d3_idx'),
        ),
        migrations.AddIndex(
            model_name='functioncalllog',
            index=models.Index(fields=['request_log', 'started_at'], name='core_functi_request_9657c8_idx'),
        ),
        migrations.AddIndex(
            model_name='functioncalllog',
            index=models.Index(fields=['function_name', '-started_at'], name='core_functi_functio_6a8e66_idx'),
        ),
        migrations.AddIndex(
            model_name='functioncalllog',
            index=models.Index(fields=['user', '-started_at'], name='core_functi_user_id_784bb2_idx'),
        ),
        migrations.AddIndex(
            model_name='functioncalllog',
            index=models.Index(fields=['status', '-started_at'], name='core_functi_status_a8bfab_idx'),
        ),
    ]
