# Generated by Django 6.0.5 on 2026-09-18 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_notification_core_notifi_recipie_b4f908_idx_and_more'),
        ('words', '0001_initial'),
    ]

    # Modeller words uygulamasına taşındı. Tablolar yerinde duruyor; burada
    # yalnızca core'un model durumu temizleniyor, DB'ye dokunulmuyor.
    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
            migrations.RemoveField(
                model_name='word',
                name='categories',
            ),
            migrations.RemoveField(
                model_name='word',
                name='user',
            ),
            migrations.AlterField(
                model_name='comment',
                name='word',
                field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='words.word'),
            ),
            migrations.AlterField(
                model_name='notification',
                name='word',
                field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='words.word'),
            ),
            migrations.RemoveField(
                model_name='wordvote',
                name='word',
            ),
            migrations.AlterUniqueTogether(
                name='wordvote',
                unique_together=None,
            ),
            migrations.RemoveField(
                model_name='wordvote',
                name='user',
            ),
            migrations.DeleteModel(
                name='Category',
            ),
            migrations.DeleteModel(
                name='Word',
            ),
            migrations.DeleteModel(
                name='WordVote',
            ),
        ],
            database_operations=[],
        ),
    ]
