# Generated by Django 6.0.5 on 2026-09-18 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_word_categories_remove_word_user_and_more'),
        ('words', '0003_comment_commentvote_and_more'),
    ]

    # Modeller words uygulamasına taşındı; tablolar yerinde, DB'ye dokunulmuyor.
    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
            migrations.RemoveIndex(
                model_name='comment',
                name='core_commen_word_id_1d0a38_idx',
            ),
            migrations.AlterField(
                model_name='notification',
                name='comment',
                field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='words.comment'),
            ),
            migrations.RemoveField(
                model_name='comment',
                name='user',
            ),
            migrations.RemoveField(
                model_name='comment',
                name='word',
            ),
            migrations.DeleteModel(
                name='CommentVote',
            ),
            migrations.DeleteModel(
                name='Comment',
            ),
        ],
            database_operations=[],
        ),
    ]
