# Generated by Django 6.0.5 on 2026-09-18 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_comment_core_commen_word_id_1d0a38_idx_and_more'),
    ]

    # Model notifications uygulamasına taşındı; tablo yerinde, DB'ye dokunulmuyor.
    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
            migrations.RemoveIndex(
                model_name='notification',
                name='core_notifi_recipie_b7a566_idx',
            ),
            migrations.DeleteModel(
                name='Notification',
            ),
        ],
            database_operations=[],
        ),
    ]
