# Generated by Django 6.0.5 on 2026-09-18 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # Word/WordVote/Category fiziksel olarak core_* tablolarında zaten var.
    # Bu migration yalnızca Django'nun model durumunu (state) taşır; veritabanına
    # hiçbir şey yapmaz. Gerçek tablo yeniden adlandırması 0002'de.
    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
            migrations.CreateModel(
                name='Category',
                fields=[
                    ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('name', models.CharField(max_length=30)),
                    ('slug', models.SlugField(unique=True)),
                    ('description', models.CharField(max_length=150)),
                    ('order', models.IntegerField(default=0)),
                    ('is_active', models.BooleanField(default=True)),
                ],
                options={
                    'verbose_name_plural': 'Categories',
                    'db_table': 'core_category',
                    'ordering': ['order', 'name'],
                },
            ),
            migrations.CreateModel(
                name='Word',
                fields=[
                    ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('word', models.CharField(max_length=50)),
                    ('slug', models.SlugField(max_length=80, null=True, unique=True)),
                    ('definition', models.CharField(max_length=300)),
                    ('example', models.CharField(default='', max_length=200)),
                    ('etymology', models.CharField(default='', max_length=200)),
                    ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                    ('author', models.CharField(default='Anonim', max_length=50)),
                    ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10)),
                    ('rejection_reason', models.CharField(blank=True, default='', max_length=300)),
                    ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                    ('score', models.IntegerField(db_index=True, default=0)),
                    ('categories', models.ManyToManyField(blank=True, related_name='words', to='words.category')),
                    ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='words', to=settings.AUTH_USER_MODEL)),
                ],
                options={
                    'db_table': 'core_word',
                },
            ),
            migrations.CreateModel(
                name='WordVote',
                fields=[
                    ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                    ('value', models.SmallIntegerField(choices=[(1, 'Like'), (-1, 'Dislike')])),
                    ('timestamp', models.DateTimeField(auto_now_add=True)),
                    ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_votes', to=settings.AUTH_USER_MODEL)),
                    ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='words.word')),
                ],
                options={
                    'db_table': 'core_wordvote',
                    'unique_together': {('user', 'word')},
                },
            ),
        ],
            database_operations=[],
        ),
    ]
