# Generated by Django 6.0.5 on 2026-09-18 14:35

from django.db import migrations


class Migration(migrations.Migration):

    # Fiziksel tablo yeniden adlandırması: core_word -> words_word vb.
    # core/0026 (durum taşıması) tamamlanmadan çalışmamalı, bu yüzden açık bağımlılık.
    dependencies = [
        ('words', '0001_initial'),
        ('core', '0026_remove_word_categories_remove_word_user_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
        migrations.AlterModelTable(
            name='word',
            table=None,
        ),
        migrations.AlterModelTable(
            name='wordvote',
            table=None,
        ),
    ]
