# Generated by Django 6.0.5 on 2026-09-18 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_rename_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # Comment/CommentVote fiziksel olarak core_* tablolarında zaten var.
    # Yalnızca model durumu taşınır; gerçek yeniden adlandırma 0004'te.
    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
            migrations.CreateModel(
                name='Comment',
                fields=[
                    ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('author', models.CharField(default='Anonim', max_length=50)),
                    ('comment', models.CharField(max_length=200)),
                    ('timestamp', models.DateTimeField(auto_now_add=True)),
                    ('score', models.IntegerField(db_index=True, default=0)),
                    ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL)),
                    ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='words.word')),
                ],
                options={
                    'db_table': 'core_comment',
                },
            ),
            migrations.CreateModel(
                name='CommentVote',
                fields=[
                    ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                    ('value', models.SmallIntegerField(choices=[(1, 'Like'), (-1, 'Dislike')])),
                    ('timestamp', models.DateTimeField(auto_now_add=True)),
                    ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='words.comment')),
                    ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_votes', to=settings.AUTH_USER_MODEL)),
                ],
                options={
                    'db_table': 'core_commentvote',
                },
            ),
            migrations.AddIndex(
                model_name='comment',
                index=models.Index(fields=['word', 'timestamp'], name='core_commen_word_id_1d0a38_idx'),
            ),
            migrations.AlterUniqueTogether(
                name='commentvote',
                unique_together={('user', 'comment')},
            ),
        ],
            database_operations=[],
        ),
    ]
