# Generated by Django 6.0.5 on 2026-09-18 14:51

from django.db import migrations


class Migration(migrations.Migration):

    # Fiziksel yeniden adlandırma: core_comment -> words_comment vb.
    # core/0027 (durum taşıması) bitmeden çalışmamalı.
    dependencies = [
        ('words', '0003_comment_commentvote_and_more'),
        ('core', '0027_remove_comment_core_commen_word_id_1d0a38_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='comment',
            new_name='words_comme_word_id_859436_idx',
            old_name='core_commen_word_id_1d0a38_idx',
        ),
        migrations.AlterModelTable(
            name='comment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='commentvote',
            table=None,
        ),
    ]
