# Generated by Django 6.0 on 2026-04-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationchallenge',
            name='winner_word_created',
            field=models.BooleanField(default=False),
        ),
    ]
