# Generated by Django 6.0 on 2026-04-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_add_winner_word_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengecomment',
            name='etymology',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='challengecomment',
            name='example_sentence',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
