# Generated by Django 6.0 on 2026-04-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_shrink_etymology_example'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationchallenge',
            name='rejection_reason',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='translationchallenge',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10),
        ),
    ]
