# Generated by Django 6.0 on 2026-04-07 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0004_translationchallenge_rejection_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengecomment',
            name='explanation',
        ),
    ]
