# Generated by Django 6.0 on 2026-04-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0005_remove_challengecomment_explanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengecomment',
            name='etymology',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='challengecomment',
            name='example_sentence',
            field=models.CharField(max_length=200),
        ),
    ]
