# Generated by Django 6.0 on 2026-04-11 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0007_challengecomment_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='challengecomment',
            new_name='core_challe_challen_ff213f_idx',
            old_name='challenge_cc_challenge_score_idx',
        ),
    ]
