# Generated by Django 6.0.5 on 2026-10-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(help_text="Bu IP'den gelen istekler 403 alır. Değişiklik en geç 30 saniye içinde tüm worker'larda etkili olur.", unique=True, verbose_name='IP')),
                ('reason', models.CharField(blank=True, default='', max_length=200, verbose_name='Sebep')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yasaklanma zamanı')),
            ],
            options={
                'verbose_name': 'Yasaklı IP',
                'verbose_name_plural': "Yasaklı IP'ler",
                'ordering': ['-created_at'],
            },
        ),
    ]
