# Generated by Django 6.0.5 on 2026-09-18 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('words', '0004_rename_comment_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # Notification fiziksel olarak core_notification tablosunda zaten var.
    # Yalnızca model durumu taşınır; gerçek yeniden adlandırma 0002'de.
    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
            migrations.CreateModel(
                name='Notification',
                fields=[
                    ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('notification_type', models.CharField(choices=[('word_like', 'Word Like'), ('word_dislike', 'Word Dislike'), ('comment_like', 'Comment Like'), ('comment_dislike', 'Comment Dislike'), ('new_comment', 'New Comment'), ('word_rejected', 'Word Rejected')], max_length=20)),
                    ('message', models.CharField(blank=True, default='', max_length=300)),
                    ('is_read', models.BooleanField(db_index=True, default=False)),
                    ('is_active', models.BooleanField(db_index=True, default=True)),
                    ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                    ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                    ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='words.comment')),
                    ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                    ('word', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='words.word')),
                ],
                options={
                    'db_table': 'core_notification',
                    'ordering': ['-timestamp'],
                    'indexes': [models.Index(fields=['recipient', 'is_active', 'is_read', '-timestamp'], name='core_notifi_recipie_b7a566_idx')],
                },
            ),
        ],
            database_operations=[],
        ),
    ]
