# Generated by Django 6.0.5 on 2026-09-18 15:05

from django.db import migrations


class Migration(migrations.Migration):

    # Fiziksel yeniden adlandırma: core_notification -> notifications_notification.
    # core/0028 (durum taşıması) bitmeden çalışmamalı.
    dependencies = [
        ('notifications', '0001_initial'),
        ('core', '0028_remove_notification_core_notifi_recipie_b7a566_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_393d29_idx',
            old_name='core_notifi_recipie_b7a566_idx',
        ),
        migrations.AlterModelTable(
            name='notification',
            table=None,
        ),
    ]
