# Generated by Django 6.0.5 on 2026-09-25 22:00

from django.db import migrations, models


def delete_challenge_notifications(apps, schema_editor):
    Notification = apps.get_model('notifications', 'Notification')
    Notification.objects.filter(
        notification_type__startswith='challenge_'
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_rename_table'),
    ]

    operations = [
        migrations.RunPython(delete_challenge_notifications, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('word_like', 'Word Like'), ('word_dislike', 'Word Dislike'), ('comment_like', 'Comment Like'), ('comment_dislike', 'Comment Dislike'), ('new_comment', 'New Comment'), ('word_rejected', 'Word Rejected')], max_length=20),
        ),
    ]
